// <auto-generated />
using System;
using EnergyCo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyCo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnergyCoDbContext))]
    partial class EnergyCoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EnergyCo.Domain.Products.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("EnergyCo.Domain.Promotions.DiscountPromotion", b =>
                {
                    b.Property<string>("DiscountPromotionId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DiscountPromotionId");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("DiscountPromotions", (string)null);
                });

            modelBuilder.Entity("EnergyCo.Domain.Promotions.DiscountPromotionProduct", b =>
                {
                    b.Property<string>("DiscountPromotionId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("DiscountPromotionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DiscountPromotionProducts", (string)null);
                });

            modelBuilder.Entity("EnergyCo.Domain.Promotions.PointsPromotion", b =>
                {
                    b.Property<string>("PointsPromotionId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationBasis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsPerDollar")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PointsPromotionId");

                    b.HasIndex("StartDate", "EndDate", "Category");

                    b.ToTable("PointsPromotions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
